version: '3.8'

services:
  sequential-thinking:
    build:
      context: .
      dockerfile: Dockerfile
    image: sequential-thinking-mcp
    container_name: sequential-thinking-mcp
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').request({port: 3000, path: '/health', timeout: 5000}, res => res.statusCode === 200 ? process.exit(0) : process.exit(1)).on('error', () => process.exit(1)).end()"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
